application:
  base-package:
    scan: com.fsk.airline.reservation.app,com.fsk.airline.reservation.persistence
  stubs:
    active: true
  test-data:
    generate: true
  messaging:
    broker:
      embedded: true
    host: localhost
    port: 5672
    queue:
      reserved-ticket:
        name: rabbitMqQueue

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:embedded
    username: admin
    password: pwd
  jpa:
    show-sql: true
    generate-ddl: true

