application:
  base-package:
    scan: com.fsk.airline.reservation.app,com.fsk.airline.reservation.persistence
  stubs:
    active: true
  test-data:
    generate: false
  messaging:
    broker:
      embedded: false
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    queue:
      reserved-ticket:
        name: ${RABBIT_MQ_RESERVED_TICKET_QUEUE}

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true
    generate-ddl: false
