application:
  base-package:
    scan: com.fsk.airline.reservation.app,com.fsk.airline.reservation.persistence
  stubs:
    active: true
  test-data:
    generate: false
  messaging:
    broker:
      embedded: false
    host: localhost
    port: 5672
    queue:
      name: rabbitMqQueue

spring:
  datasource:
    url: jdbc:mysql:blablabla
    username: admin
    password: pwd
  jpa:
    show-sql: true
    generate-ddl: false
